<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>AutoPipCollector</AssemblyName>
    <Product>Auto-Pip Collector</Product>
    <Version>2.3.0</Version>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <DebugType>none</DebugType>
    <SatelliteResourceLanguages>en</SatelliteResourceLanguages>
    <ApplicationIcon>icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.*" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\painel\painel.html">
      <LogicalName>painel.html</LogicalName>
    </EmbeddedResource>
    <EmbeddedResource Include="icon.ico">
      <LogicalName>icon.ico</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

</Project>
